### ISSUE TITLE
livejquery not working with ie7 ie8 

### ISSUE THREAD

**Issue by botsbrain** [brandonaaron/livequery#13]
livejquery not working with ie7 ie8

**Comment by mikesherov** [comment]
What specifically isn't working.

**Comment by mbhandek** [comment]
Hi,

For us with livequery js v1.1.1 ... we are getting heavy CPU usage ~80% just after the page gets loaded and even if we just keep the IE8 browser open. Same code base and same livequery js works fine on IE9 and other web-browsers.

If we use developer tools and start profiling and keep it on for 30min or so, we see heavy calls to checkQueue method.
The call tree view shows following call trace -

``` code
Method                     Count        Inclusive Time (ms)  Incl Time %       Excl Time (ms)
checkQueue          5,541   2,368,856.46          94.83        3,588.87         
            run         664,920 2,362,546.88          94.58        9,349.62 
                 not        664,920 960,977.54        38.47        2,281.25         
                 d          664,920 456,903.33        18.29        1,527.34         
                 bind   343,542 6,050.78                  0.24          744.14          
                 each   321,378 2,698.24                  0.11          640.62          
                 each   77,574  926,567.37        37.09         4,731.44             
             Array.shift    664,920 2,720.71                  0.11          2,720.71            
```

I hope the profiler log helps.

**Comment by brandonaaron** [comment]
How many "live queries" are you using? Are you using this plugin primarily to attach events? If so, switch to the delegate method within jQuery.

**Comment by mbhandek** [comment]
Thanks for quick reply!

Not sure what you mean by "how many live queries". We are just using single js library.

Yes we are using the plugin to attach events.

You are saying we shouldn't use livequery for attaching events is that correct?
You mean http://api.jquery.com/delegate/ when you say delegate?

**Comment by brandonaaron** [comment]
Yeah, delegate will give you huge performance gains for binding events.

Re: "how many live queries"... In other words: How many times are you using the plugin to bind events?

**Comment by mbhandek** [comment]
We replaced events with jquery 'on' function. But we are still getting un reasonable CPU usage.

We are using livequery for following -

  $('.edit_in_place').livequery(function(){
      $(this).editInPlace();
  });

Do you have any idea how we can work around get zero CPU usage for such usage on IE7 and IE8?
Also, are you by any chance suggesting that we shouldn't be using livequery if we wanted IE7 and IE8 support?
