### ISSUE TITLE
Move master to a versioned branch or tag it (or both), and move mutated to master

### ISSUE THREAD

**Issue by PikachuEXE** [brandonaaron/livequery#18]
Just not to confuse people that this repo is inactive

**Comment by brandonaaron** [comment]
Yeah, I should probably do something so that people are more aware that there is some "active" development happening. I'm hoping that in about 2 weeks I'll have some time to give to this project.

**Comment by brandonaaron** [comment]
Went ahead and responded to some of the older issues here and moved mutated to master. Thanks for the nudge to get this done.
