### ISSUE TITLE
livequery matchedFn executed multiple times for one element

### ISSUE THREAD

**Issue by dennishall** [brandonaaron/livequery#9]
&lt;div class="foo"&gt;
this is the one and only foo element
&lt;/div&gt;

---

$('.foo').livequery(function(){
console.log(' we have a NEW foo ');
});
// you see console.log happen

$('.foo').addClass('bar');
// you see console.log happen again, for the same element, even though it is not a new element.

**Comment by brandonaaron** [comment]
This shouldn't be an issue anymore with the new rewrite currently happening.
